spring.application.name=lanches
# Configura??o recomendada para o Freemarker
spring.freemarker.template-loader-path=classpath:/templates
spring.freemarker.suffix=.html
spring.freemarker.cache=false
spring.freemarker.charset=UTF-8
spring.freemarker.check-template-location=true
spring.freemarker.content-type=text/html

# Configuração do DataSource (H2 baseado em arquivo)
# O banco será salvo na pasta 'data' dentro do projeto com o nome 'snackdb'
spring.datasource.url=jdbc:h2:file:./data/snackdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Configuração do Dialeto Hibernate
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Habilita o Console do H2 (acessível em /h2-console)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Criação do banco de dados ao iniciar
# 'update' atualiza o esquema sem apagar dados. Use 'create-drop' para resetar sempre.
spring.jpa.hibernate.ddl-auto=update

# Opcional: Mostra o SQL no log para debug
spring.jpa.show-sql=true
